### ISSUE TITLE
Añadir licencia

### ISSUE THREAD

**Issue by astrojuanlu** [alexmacastro/AE_FEM#1]
Antes de nada, mi enhorabuena y agradecimiento a los autores de estos materiales porque son espectaculares :) Aparte de, hasta donde sé, pioneros.

¿Podríais añadir alguna licencia para clarificar en qué términos se pueden reutilizar estos materiales? Entiendo que si los publicáis en GitHub es porque buscáis su difusión, pero [faltaría una licencia](http://es.stackoverflow.com/a/363/74).

Por ejemplo, para nuestros materiales de AeroPython utilizamos Creative Commons con Atribución (ver https://github.com/AeroPython/curso_caminos-2016/blob/master/README.md).

**Comment by alexmacastro** [comment]
Buenos días, 

Ante todo, mil enhorabuenas por tus excelentes contribuciones al mundo de Python. Es para mí todo un honor que me escribas, ya que de una forma u otra he seguido tus vídeos y cuadernos, y los recomiendo a mis estudiantes. 

Soy un humilde iniciado a este mundo de Python, el cual he conocido como alumno de varios cursos de Coursera. Imparto docencia en la ETS de Ingenieros de Caminos, Canales y Puertos de Granada, en estructuras. Trabajo en sólidos, fluidos, desde los métodos numéricos. Para mí, no hay forma mejor de explicar Elementos Finitos (FEM) que utilizar estos cuadernos, ya que se evitan horas y horas de escribir en pizarra cuestiones repetitivas. Para el alumno es muy potente, porque con estos cuadernos es capaz de obtener por sí mismo funciones de forma, matrices de rigidez, sin necesidad de hacer "actos de fe". Los libros tradicionales de FEM son muy estáticos, y creo que el futuro en la enseñanza de FEM requiere cuadernos de Jupyter interactivos. 

Respecto al tema que me comentas de la licencia, reconozco que ignoro mucho aún del tema de la licencia Creative Commons. Yo mismo he subido en el pasado documentos, a través de una plataforma de la Universidad de Granada, y nunca me quedó claro los límites ni las implicaciones. Me aparecía un cuadro de diálogo tipo ¿quiere usted protegerlo con licencia Creative Commons?. Le decía que sí, y poco más. Nadie me ha pedido ponerle un logotipo de CC, ni sé exactamente qué implicaciones tiene ponerlo o no ponerlo. 

Sobre el material de AE_FEM, si lo he subido a github público es para que cualquiera que lo desee se lo descargue, lo modifique y haga lo que quiera con el material. ¿Añadirle una licencia?. Pues no me lo había ni planteado. Hay muchísimo material en github sin esa licencia, y se entiende que el usuario es responsable de usarlo, modificarlo y citar. Pero reitero, soy un ignorante en cuanto a los límites de esta licencia. Lo que no me gustaría es añadir algún tipo de restricción a lo que pretendo: la libre redistribución para uso y modificación por parte de cualquiera. 

Respecto al material que tienes en AeroPython, yo mismo lo conozco, es muy bueno. Yo mismo he adaptado algún cuaderno para mis alumnos, pasándolo a Python 2.7 (trabajamos así porque ciertos paquetes informáticos, como Salome-Meca, etc, traen una shell de Python basado en el 2.7 aún). Ignoro los temas de la licencia, y hasta donde sabía, entiendo que cualquiera puede modificar, redistribuir, etc, citando la fuente. Siempre he citado las fuentes, y verbalmente a mis alumnos he recomendado para ciertas cosas ir a las fuentes, claro. Lo que yo haya modificado es porque ha sido necesario para ellos. 

Voy a informarme mejor de este tema de la licencia Creative Commons en relación al material de github, para añadir la licencia a lo que yo haga, y para citar e incluir adecuadamente las referencias a lo que tome de otros. 

Gracias por tu mensaje, 
Alejandro

**Comment by astrojuanlu** [comment]
Hola Alejandro:

Muchas gracias a ti por tu extensa respuesta, me asombra saber que nuestro trabajo tiene esta repercusión :)

Estoy totalmente de acuerdo contigo en que los cuadernos de Jupyter tienen un potencial tremendo, y que van a dejar atrás a los métodos de enseñanza tradicionales. Es cuestión de tiempo que los vayamos aplicando a diferentes temáticas, y en concreto me encantó descubrir estos sobre estructuras.

El tema de la licencia es importante porque, según los tratados internacionales (convenio de Berna) el "copyright" es irrenunciable, es decir: cuando se publica cualquier cosa (en Internet o en medios tradicionales) por defecto tiene "todos los derechos reservados". Es por eso por lo que se deben adjuntar licencias que "liberen" el contenido de estas ataduras. De hecho, este malentendido está tremendamente extendido - en 2013, solo el 15 % de los proyectos de GitHub tenían licencia http://www.theregister.co.uk/2013/04/18/github_licensing_study/

De nuevo muchas gracias por tu trabajo y seguimos en contacto. ¡Un saludo!

**Comment by alexmacastro** [comment]
Buenas, 
Ya he añadido la licencia a los ficheros.  He esperado a tenerlos en el curso actualizados. Tengo que generar otras versiones para Python 3. 
Espero que esté todo bien ahora. 
Gracias

**Comment by astrojuanlu** [comment]
Estupendo, muchas gracias :) ¡Cerrando!
